name: Build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      os:
        required: true
        type: string
      buildArgs:
        required: true
        type: string
      assetType:
        required: true
        type: string
      artifactName:
        required: true
        type: string
      artifactPath:
        required: true
        type: string

env:
  HAXE_VERSION: 4.3.7
  PROJECT_NAME: HorrorPackage

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        if: inputs.name != 'Linux ARM64' && inputs.name != 'Linux ARMV7'
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - name: Setup Haxe (Linux ARM)
        if: inputs.name == 'Linux ARM64' || inputs.name == 'Linux ARMV7'
        run: |
          sudo add-apt-repository ppa:haxe/releases -y
          sudo apt update
          sudo apt-get install -y haxe neko
          haxelib setup ~/haxelib

      - name: Install Dependencies for Linux
        if: startsWith(inputs.name, 'Linux')
        shell: bash
        run: |
          case "${{ inputs.name }}" in
            "Linux i686")
              sudo dpkg --add-architecture i386
              sudo apt update
              sudo apt install -y gcc-multilib g++-multilib
              ;;
            "Linux ARMV7")
              sudo dpkg --add-architecture armhf
              sudo apt update
              sudo apt install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
              ;;
          esac

      - name: Setup Android NDK for Legacy
        if: inputs.name == 'Android (Legacy)'
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r25c
          add-to-path: false

      - name: Install Libraries
        run: |
          haxelib git hmm https://github.com/ShadowEngineTeam/hmm --skip-dependencies --quiet
          haxelib run hmm install --quiet
          if [[ "${{ inputs.name }}" == "Android (Legacy)" ]]; then
            cd $(haxelib libpath lime)
            git checkout --detach android-legacy
          fi

      - name: Configure Android
        if: inputs.name == 'Android'
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          if [[ "${{ inputs.name }}" == "Android (Legacy)" ]]; then
            rm -rf $ANDROID_HOME/build-tools/*
            yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager.bat "build-tools;29.0.3" --sdk_root="$ANDROID_HOME"
            haxelib run lime config ANDROID_NDK_ROOT ${{ steps.setup-ndk.outputs.ndk-path }}
            haxelib run lime config JAVA_HOME $JAVA_HOME_11_arm64
          else
            haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
            haxelib run lime config JAVA_HOME $JAVA_HOME_21_arm64
          fi
          haxelib run lime config ANDROID_SETUP true

      - name: Compile
        shell: bash
        run: |
          case "${{ inputs.name }}" in
            "Linux ARMV7")
              CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ linux32 haxelib run lime build ${{ inputs.buildArgs }} -D ${{ inputs.assetType }}
              ;;
            *)
              haxelib run lime build ${{ inputs.buildArgs }} -D ${{ inputs.assetType }}
              ;;			  
          esac

      - name: Make IPA
        if: inputs.name == 'iOS'
        run: |
          brew install ldid
          cd export/release/ios/build/Release-iphoneos/${{ env.PROJECT_NAME }}.app
          ldid -S../../../${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.entitlements ${{ env.PROJECT_NAME }}
          cd ..
          mkdir Payload
          mv ${{ env.PROJECT_NAME }}.app Payload
          zip -r ${{ env.PROJECT_NAME }}.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ inputs.artifactName }}-${{ inputs.assetType }}
          path: ${{ inputs.artifactPath }}
          if-no-files-found: error
